# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20160725_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
