# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-25 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20160725_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
